Fix version check for display width modifier support in unit tests for MySQL
joomla-framework/database pull request #242
Opened 2021-03-24 12:08 UTC by richard67

Pull Request for Issue #241 .

### Summary of Changes

This pull request (PR) changes the 2 checks for display width modifier support in unit tests for the MySQL drivers so the check is correctly done if it's a MariaDB or a MySQL version lower than 8.0.17, which still use the display width modifier for integer data types, or if it's a MySQL 8.0.17 or later, on which the display width modifier is deprecated and not part of the column's type specifier returned e.g. by a "SHOW COLUMNS" and where it might not be supported in future.

### Testing Instructions

Check if unit tests still pass.

### Documentation Changes Required

None.

### Additional information

I might do a follow-up PR later to remove the usage of the display width modifier from SQL statements in scripts and at other places.

2021-03-24 12:27 UTC, richard67 commented
@nibra Does it also need a PR for the 2.0-dev branch? Or is this something which will be merged up to there from master?

2021-03-24 12:37 UTC, richard67 commented
> @nibra Does it also need a PR for the 2.0-dev branch? Or is this something which will be merged up to there from master?

Update: I just see tests have been changed there, so I have to make a separate PR.

2021-03-24 13:00 UTC, richard67 commented
For 2.0-dev see #243 .

2021-03-24 13:20 UTC, nibra requested changes

2021-03-24 13:20 UTC, nibra commented on Tests/DriverMysqlTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
`stripos()` needs to be tested against `false`, because 0 means that the string starts with 'mariadb'.
Doesn't it make more sense to test for MySQL, as *that* changes behaviour?

2021-03-24 13:20 UTC, nibra commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
`stripos()` needs to be tested against `false`, because 0 means that the string starts with 'mariadb'.
Doesn't it make more sense to test for MySQL, as *that* changes behaviour?

2021-03-24 13:25 UTC, richard67 commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
> Doesn't it make more sense to test for MySQL, as that changes behaviour?

What do yo mean with that? Change (invert) the logic?

2021-03-25 09:00 UTC, nibra commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
Yes, `stripos($version, 'mysql') && version_compare($version, '8.0.17') >= 0 ? 'int unsigned' : 'int(10) unsigned'`

2021-03-25 09:15 UTC, richard67 commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
This would be wrong, I think you mean:

`stripos($version, 'mysql') === false && version_compare($version, '8.0.17') >= 0 ? 'int unsigned' : 'int(10) unsigned'`

What means "does it make more sense"? Both make same sense, my current implementation here is even better because in case of mariadb has to check only one term. And I think it's better readable, too.

And in the 2.0-dev branch you have already merged that with the same logic, only difference is we could use the IsMariaDB (or so) function.

2021-03-25 09:18 UTC, richard67 commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
After this one will be merged, there will be one thing left to do on both branches: Fix the XML import so it strips off the display with on MySQL 8.0.17 or later. There I might use indeed inverse logic because it would make later checks not to be inverted. But that really depends on the context, what's better at that place.

2021-03-25 16:22 UTC, nibra commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
`stripos($version, 'mysql') !== false` says that `$version` contains 'mysql'.
`version_compare($version, '8.0.17') >= 0` says the version is 8.0.17+.
That would change behavoiur for *MySQL 8.0.17+* and not for *any other than MariaDB with a version >= 8.0.17*, which makes the intention much more obvious.

2021-03-25 17:52 UTC, richard67 commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
Ah i didn't get the change with the stipos argument. Anyway, you have merged the same logic into 2.0-dev, so I see no reason to change it here.

2021-03-28 13:56 UTC, richard67 commented on Tests/DriverMysqliTest.php
> +		$id->Type       = stripos($version, 'mariadb') || version_compare($version, '8.0.17') < 0 ? 'int(10) unsigned' : 'int unsigned';
See here for the 2.0-dev logic: https://github.com/joomla-framework/database/blob/2.0-dev/Tests/Mysql/MysqlDriverTest.php#L94

2021-03-29 11:14 UTC, merged

2021-03-29 11:14 UTC, nibra commented
Thank you!