Replace getQuery(true) with createQuery(), deprecate $new parameter
joomla-framework/database pull request #274
Opened 2023-01-17 15:08 UTC by HLeithner

Since using a boolean parameter is a bad pattern and setting the parameter to true to get a new object is miss understandable and makes it hard for new comers to use the API.

The pull requests create a new method `createQuery()` which always returns a new databasequery. It also depreacte and mark the true parameter for removal in version 4.0

2023-01-17 16:05 UTC, laoneo commented
I think the tests should not be changed. Instead add new test functions which do test the new function.

2023-01-17 16:11 UTC, HLeithner commented
The functionality it self is tested at https://github.com/joomla-framework/database/blob/2.0-dev/Tests/DatabaseFactoryTest.php#L261-L272

if we keep getQuery(true) in the test they will issue deprecation warnings. Maybe a new test for ->getQuery(true) which expects an deprecation warning make sense.

In v3 the interface should also get the new method.

2023-01-17 23:46 UTC, wilsonge commented
I don't think having a boolean param is inherently bad. But in this case given it's the majority use case it definitely makes sense to separate this so :+1:

2023-01-20 07:03 UTC, SharkyKZ requested changes

2023-01-20 07:03 UTC, SharkyKZ commented on src/DatabaseDriver.php
> +	 * @return  DatabaseQuery
This should really be `QueryInterface`. The doc in `getQuery()` should be fixed too.

2023-01-20 07:03 UTC, SharkyKZ commented on src/DatabaseDriver.php
> +	 * @since   2.1
2.1 is already out. Does this repo not support `__DEPLOY_VERSION__` placeholder?

2023-01-20 07:03 UTC, SharkyKZ commented on src/DatabaseDriver.php
> +	public function createQuery()
Add return type.

2023-01-20 07:03 UTC, SharkyKZ commented on src/DatabaseDriver.php
> +	 * @deprecated  4.0  $new parameter will be removed, use createQuery() method instead.
The method is not deprecated...

2023-01-20 07:03 UTC, SharkyKZ commented on src/DatabaseDriver.php
> +				'2.1.0',
2.1 is already out...

2023-01-20 07:03 UTC, SharkyKZ commented on src/DatabaseDriver.php
> +				'getQuery(true) call is deprecated and will be removed in 4.0, use createQuery() instead.',
Use full method names. Also, it's the parameter, not the method that's deprecated. Remove trailing comma.

2023-01-20 07:03 UTC, SharkyKZ commented on src/DatabaseExporter.php
> +				$this->db->createQuery()
Revert.

2023-01-20 07:03 UTC, SharkyKZ commented on src/Pgsql/PgsqlExporter.php
> +			$query = $this->db->createQuery();
Revert.

2023-01-20 07:52 UTC, HLeithner commented on src/DatabaseExporter.php
> +				$this->db->createQuery()
Why?

2023-01-20 07:52 UTC, HLeithner commented on src/Pgsql/PgsqlExporter.php
> +			$query = $this->db->createQuery();
Why? It requests a new database query isn't it?

2023-01-20 07:52 UTC, HLeithner commented on src/DatabaseDriver.php
> +	 * @return  DatabaseQuery
Changed, not sure about the docs in `getQuery()`, it's completely wrong, because it could return the `interface` or a `string` (and base on `$this->sql` it could be `mixed`)

2023-01-20 07:52 UTC, HLeithner commented on src/DatabaseDriver.php
> +	 * @since   2.1
Since jenkins is gone there is no bump script anymore afaik...

2023-01-20 07:52 UTC, HLeithner commented on src/DatabaseDriver.php
> +	public function createQuery()
done

2023-01-20 07:56 UTC, SharkyKZ commented on src/DatabaseExporter.php
> +				$this->db->createQuery()
You can't use this here until the method is added to the interface.

2023-01-20 08:15 UTC, HLeithner commented on src/DatabaseExporter.php
> +				$this->db->createQuery()
true

2023-03-16 19:37 UTC, HLeithner commented
@nibra @Llewellynvdm would we like to merge this?

2023-03-17 02:18 UTC, Llewellynvdm commented
Please re-base, and I will merge this.

2023-03-21 10:48 UTC, HLeithner commented
on 3?, I think adding it to a 2.x minor makes the b/c better for extensions developer

2023-03-21 11:34 UTC, wilsonge commented
I agree adding this into the 2.x minor makes more sense to help with migration paths

2023-03-21 11:35 UTC, wilsonge requested changes
I think we should leave one test in using `getQuery(true)` to test the legacy behavior still works (happy with moving the majority of test to the new style)

2023-03-21 11:41 UTC, HLeithner commented
Created a new test based on loadAssoc using the deprecated syntax.

2023-03-21 11:47 UTC, Llewellynvdm commented
Yes I was think 2 as well.

2023-03-21 13:11 UTC, wilsonge approved these changes

2023-03-21 13:51 UTC, merged